#!/usr/bin/env bash
#Job name
#SBATCH -J nsp83_4
# Asking for N nodes
#SBATCH -N 8
# Request a particular cluster
#SBATCH -p longq
# Output results message
#SBATCH -o nonsplit-p83-chunk4-%j-output.txt
# Output error message
#SBATCH -e nonsplit-p83-chunk4-%j-errors.txt
# time_limit
#SBATCH -t 4320
# number of processes 
#SBATCH -c 24
#SBATCH --exclusive
p=83
chunk=4
numChunks=6
module purge
module load editor
module load slurm mpi/openmpi
module load formal
echo "=====my job informations ==== "echo "Node List: " $SLURM_NODELIST
echo "my jobID: " $SLURM_JOB_ID
echo "Partition: " $SLURM_JOB_PARTITION
echo "submit directory:" $SLURM_SUBMIT_DIR
echo "submit host:" $SLURM_SUBMIT_HOST
echo "In the directory: `pwd`"
echo "As the user: `whoami`"
echo "p = " $p
echo "chunk = " $chunk
echo "numChunks = " $numChunks
mpirun bash ./nonsplit_for_83_inChunksAndParts_node.sh $p $chunk $numChunks


